import { NextPage } from "next";
import Head from "next/head";

const HeadCustom: NextPage = () => {
    return (
        <Head>
            <title>Tsukasa Renato</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default HeadCustom